# config.py
WINDOW_WIDTH = 500
WINDOW_HEIGHT = 500
FPS = 60

LIP_SYNC_SENSITIVITY = 0.7
LIP_SYNC_SMOOTHING = 0.35
LIP_SYNC_THRESHOLD = 0.005

TTS_VOICE = "af_heart"
SAMPLE_RATE = 22050
FRAME_SIZE = 441

AUDIO_NOISE_FLOOR = 1e-4
AUDIO_VOLUME_GAIN = 6.0
AUDIO_COMPRESSION = 0.8

MODEL_PATH = "models/Meta-Llama-3-8B-Instruct.Q4_1.gguf"
LIVE2D_MODEL_PATH = "live2d_models/l2d/L2DZeroVS.model3.json"

DEBUG = True
